// language.js — Comunidad Global de Fans de Conejo Malo — 12 Languages

const languages = {
  en: {
    navHome:"HOME", navCommunity:"COMMUNITY", navMembership:"MEMBERSHIP",
    navEvents:"EVENTS", navSupport:"SUPPORT", navContact:"CONTACT",
    loginBtn:"LOGIN", logoutBtn:"Logout",
    heroBadge:"🌍 GLOBAL FAN COMMUNITY",
    title:"Comunidad Global de Fans de Conejo Malo",
    subtitle:"Bad Bunny Global Fan Community",
    heroDesc:"Celebrating music, culture, and the worldwide impact of Bad Bunny. Join millions of fans across the globe.",
    statGlobal:"Global Community", statVIP:"VIP Access", statMusic:"Exclusive Content",
    joinBtn:"Join the Community", exploreBtn:"Explore",
    aboutTag:"ABOUT US", aboutTitle:"About the Community",
    aboutText:"Comunidad Global de Fans de Conejo Malo is a global fan community created to celebrate the music, culture, and worldwide impact of Bad Bunny.",
    aboutF1:"Exclusive Music", aboutF1D:"Access exclusive content, previews and curated playlists.",
    aboutF2:"Global Network", aboutF2D:"Connect with fans from USA, Spain, Mexico, Brazil, Japan and beyond.",
    aboutF3:"Fan Rankings", aboutF3D:"Earn badges and climb the ranks from New Fan to Legend Fan.",
    aboutF4:"Events Access", aboutF4D:"Early access to concert announcements and listening parties.",
    disclaimer:"⚠️ This is an independent fan community. Not officially affiliated with Bad Bunny or his management.",
    memberTag:"MEMBERSHIP", memberTitle:"Fan Membership Platform",
    memberSubtitle:"WHERE FANS CONNECT, SHARE, AND SPEAK AS ONE",
    memberDesc:"Only accessible after login. This is the heart of our global fan community.",
    tierFree:"Free", allMembersGet:"All Members Get",
    rankTitle:"Fan Ranking System", rankDesc:"Earn your rank through community participation. The more active you are, the higher you climb!",
    mapTitle:"Global Fan Map", mapDesc:"Our community spans every continent. Fans united by music.",
    eventsTitle:"Fan Events", eventsDesc:"Stay connected with listening parties, fan competitions, and concert discussions.",
    event1:"Listening Parties", event1D:"Live album listening sessions with the community.",
    event2:"Fan Competitions", event2D:"Art contests, lyric challenges, and fan polls.",
    event3:"Concert Discussions", event3D:"Live reaction threads during Bad Bunny concerts.",
    supportTitle:"Support the Community", supportDesc:"Help keep this fan community alive and growing. Every contribution matters.",
    cryptoMsg:"Contact for address", emailSupport:"✉ Email us for payment instructions and support requests.",
    contactTitle:"Get In Touch", contactDesc:"Have questions or want to collaborate? Reach out to the community team.",
    socialIG:"📸 Instagram", socialTT:"🎵 TikTok", socialFB:"👤 Facebook", socialX:"✖ X (Twitter)",
    modalTitle:"Member Login / Register", modalSub:"Join the global Bad Bunny fan community",
    emailLabel:"Email", passLabel:"Password", registerBtn:"Register", loginModalBtn:"Login",
    modalTerms:"By joining you agree to our community guidelines."
  },
  es: {
    navHome:"INICIO", navCommunity:"COMUNIDAD", navMembership:"MEMBRESÍA",
    navEvents:"EVENTOS", navSupport:"APOYO", navContact:"CONTACTO",
    loginBtn:"ENTRAR", logoutBtn:"Cerrar Sesión",
    heroBadge:"🌍 COMUNIDAD GLOBAL DE FANS",
    title:"Comunidad Global de Fans de Conejo Malo",
    subtitle:"Comunidad Global de Fans de Bad Bunny",
    heroDesc:"Celebrando la música, la cultura y el impacto mundial de Bad Bunny. Únete a millones de fans en todo el mundo.",
    statGlobal:"Comunidad Global", statVIP:"Acceso VIP", statMusic:"Contenido Exclusivo",
    joinBtn:"Únete a la Comunidad", exploreBtn:"Explorar",
    aboutTag:"SOBRE NOSOTROS", aboutTitle:"Sobre la Comunidad",
    aboutText:"Comunidad Global de Fans de Conejo Malo es una comunidad de fans creada para celebrar la música, cultura e impacto de Bad Bunny.",
    aboutF1:"Música Exclusiva", aboutF1D:"Accede a contenido exclusivo, previews y playlists.",
    aboutF2:"Red Global", aboutF2D:"Conecta con fans de USA, España, México, Brasil, Japón y más.",
    aboutF3:"Rankings de Fans", aboutF3D:"Gana insignias y sube en los rangos.",
    aboutF4:"Acceso a Eventos", aboutF4D:"Acceso anticipado a anuncios de conciertos.",
    disclaimer:"⚠️ Esta es una comunidad de fans independiente. No está afiliada oficialmente con Bad Bunny.",
    memberTag:"MEMBRESÍA", memberTitle:"Plataforma de Membresía de Fans",
    memberSubtitle:"DONDE LOS FANS SE CONECTAN, COMPARTEN Y HABLAN COMO UNO",
    memberDesc:"Solo accesible después de iniciar sesión.",
    tierFree:"Gratis", allMembersGet:"Todos los Miembros Obtienen",
    rankTitle:"Sistema de Ranking de Fans", rankDesc:"¡Gana tu rango a través de la participación en la comunidad!",
    mapTitle:"Mapa Global de Fans", mapDesc:"Nuestra comunidad abarca todos los continentes.",
    eventsTitle:"Eventos de Fans", eventsDesc:"Mantente conectado con fiestas de escucha, competencias y discusiones.",
    event1:"Fiestas de Escucha", event1D:"Sesiones de escucha de álbumes en vivo con la comunidad.",
    event2:"Competencias de Fans", event2D:"Concursos de arte, desafíos de letras y encuestas.",
    event3:"Discusiones de Conciertos", event3D:"Hilos de reacción en vivo durante los conciertos.",
    supportTitle:"Apoya la Comunidad", supportDesc:"Ayuda a mantener esta comunidad de fans viva y creciendo.",
    cryptoMsg:"Contacta para la dirección", emailSupport:"✉ Envíanos un correo para instrucciones de pago.",
    contactTitle:"Contáctanos", contactDesc:"¿Tienes preguntas? Comunícate con el equipo.",
    socialIG:"📸 Instagram", socialTT:"🎵 TikTok", socialFB:"👤 Facebook", socialX:"✖ X (Twitter)",
    modalTitle:"Login / Registro de Miembro", modalSub:"Únete a la comunidad global de fans de Bad Bunny",
    emailLabel:"Correo", passLabel:"Contraseña", registerBtn:"Registrarse", loginModalBtn:"Entrar",
    modalTerms:"Al unirte aceptas nuestras pautas de la comunidad."
  },
  fr: {
    navHome:"ACCUEIL", navCommunity:"COMMUNAUTÉ", navMembership:"ADHÉSION",
    navEvents:"ÉVÉNEMENTS", navSupport:"SOUTIEN", navContact:"CONTACT",
    loginBtn:"CONNEXION", logoutBtn:"Déconnexion",
    heroBadge:"🌍 COMMUNAUTÉ MONDIALE DE FANS",
    title:"Communauté Mondiale des Fans de Conejo Malo",
    subtitle:"Communauté Mondiale des Fans de Bad Bunny",
    heroDesc:"Célébrant la musique, la culture et l'impact mondial de Bad Bunny. Rejoignez des millions de fans.",
    statGlobal:"Communauté Mondiale", statVIP:"Accès VIP", statMusic:"Contenu Exclusif",
    joinBtn:"Rejoindre la Communauté", exploreBtn:"Explorer",
    aboutTag:"À PROPOS", aboutTitle:"À Propos de la Communauté",
    aboutText:"Une communauté mondiale de fans créée pour célébrer la musique et la culture de Bad Bunny.",
    aboutF1:"Musique Exclusive", aboutF1D:"Accédez à du contenu exclusif et des playlists.",
    aboutF2:"Réseau Mondial", aboutF2D:"Connectez-vous avec des fans du monde entier.",
    aboutF3:"Classements des Fans", aboutF3D:"Gagnez des badges et montez dans les rangs.",
    aboutF4:"Accès aux Événements", aboutF4D:"Accès anticipé aux annonces de concerts.",
    disclaimer:"⚠️ Communauté de fans indépendante. Non affiliée officiellement à Bad Bunny.",
    memberTag:"ADHÉSION", memberTitle:"Plateforme d'Adhésion des Fans",
    memberSubtitle:"OÙ LES FANS SE CONNECTENT, PARTAGENT ET PARLENT COMME UN",
    memberDesc:"Accessible uniquement après connexion.",
    tierFree:"Gratuit", allMembersGet:"Tous les Membres Obtiennent",
    rankTitle:"Système de Classement des Fans", rankDesc:"Gagnez votre rang grâce à la participation!",
    mapTitle:"Carte Mondiale des Fans", mapDesc:"Notre communauté couvre tous les continents.",
    eventsTitle:"Événements des Fans", eventsDesc:"Restez connectés avec des soirées d'écoute et des discussions.",
    event1:"Soirées d'Écoute", event1D:"Sessions d'écoute d'albums en direct.",
    event2:"Compétitions de Fans", event2D:"Concours d'art, défis de paroles et sondages.",
    event3:"Discussions de Concerts", event3D:"Fils de réaction en direct pendant les concerts.",
    supportTitle:"Soutenir la Communauté", supportDesc:"Aidez à garder cette communauté vivante.",
    cryptoMsg:"Contactez pour l'adresse", emailSupport:"✉ Envoyez-nous un email pour les instructions de paiement.",
    contactTitle:"Nous Contacter", contactDesc:"Des questions? Contactez l'équipe.",
    socialIG:"📸 Instagram", socialTT:"🎵 TikTok", socialFB:"👤 Facebook", socialX:"✖ X (Twitter)",
    modalTitle:"Connexion / Inscription", modalSub:"Rejoignez la communauté mondiale de fans",
    emailLabel:"Email", passLabel:"Mot de passe", registerBtn:"S'inscrire", loginModalBtn:"Connexion",
    modalTerms:"En vous inscrivant, vous acceptez nos directives."
  },
  pt: {
    navHome:"INÍCIO", navCommunity:"COMUNIDADE", navMembership:"MEMBROS",
    navEvents:"EVENTOS", navSupport:"APOIO", navContact:"CONTATO",
    loginBtn:"ENTRAR", logoutBtn:"Sair",
    heroBadge:"🌍 COMUNIDADE GLOBAL DE FÃS",
    title:"Comunidade Global de Fãs de Conejo Malo",
    subtitle:"Comunidade Global de Fãs de Bad Bunny",
    heroDesc:"Celebrando a música, cultura e o impacto mundial de Bad Bunny. Junte-se a milhões de fãs.",
    statGlobal:"Comunidade Global", statVIP:"Acesso VIP", statMusic:"Conteúdo Exclusivo",
    joinBtn:"Juntar-se à Comunidade", exploreBtn:"Explorar",
    aboutTag:"SOBRE NÓS", aboutTitle:"Sobre a Comunidade",
    aboutText:"Uma comunidade global de fãs criada para celebrar a música e cultura de Bad Bunny.",
    aboutF1:"Música Exclusiva", aboutF1D:"Acesse conteúdo exclusivo e playlists.",
    aboutF2:"Rede Global", aboutF2D:"Conecte-se com fãs do mundo inteiro.",
    aboutF3:"Rankings de Fãs", aboutF3D:"Ganhe emblemas e suba nos rankings.",
    aboutF4:"Acesso a Eventos", aboutF4D:"Acesso antecipado a anúncios de shows.",
    disclaimer:"⚠️ Comunidade de fãs independente. Não afiliada oficialmente ao Bad Bunny.",
    memberTag:"MEMBROS", memberTitle:"Plataforma de Membros dos Fãs",
    memberSubtitle:"ONDE OS FÃS SE CONECTAM, COMPARTILHAM E FALAM COMO UM",
    memberDesc:"Acessível apenas após login.",
    tierFree:"Grátis", allMembersGet:"Todos os Membros Recebem",
    rankTitle:"Sistema de Ranking de Fãs", rankDesc:"Ganhe seu rank através da participação na comunidade!",
    mapTitle:"Mapa Global de Fãs", mapDesc:"Nossa comunidade abrange todos os continentes.",
    eventsTitle:"Eventos de Fãs", eventsDesc:"Fique conectado com festas de escuta e discussões.",
    event1:"Festas de Escuta", event1D:"Sessões de escuta de álbuns ao vivo.",
    event2:"Competições de Fãs", event2D:"Concursos de arte, desafios de letras e enquetes.",
    event3:"Discussões de Shows", event3D:"Threads de reação ao vivo durante os shows.",
    supportTitle:"Apoie a Comunidade", supportDesc:"Ajude a manter esta comunidade viva e crescendo.",
    cryptoMsg:"Contate para o endereço", emailSupport:"✉ Envie-nos um email para instruções de pagamento.",
    contactTitle:"Entre em Contato", contactDesc:"Tem perguntas? Fale com a equipe.",
    socialIG:"📸 Instagram", socialTT:"🎵 TikTok", socialFB:"👤 Facebook", socialX:"✖ X (Twitter)",
    modalTitle:"Login / Registro de Membro", modalSub:"Junte-se à comunidade global de fãs",
    emailLabel:"Email", passLabel:"Senha", registerBtn:"Registrar", loginModalBtn:"Entrar",
    modalTerms:"Ao se juntar, você concorda com nossas diretrizes da comunidade."
  },
  de: {
    navHome:"STARTSEITE", navCommunity:"GEMEINSCHAFT", navMembership:"MITGLIEDSCHAFT",
    navEvents:"VERANSTALTUNGEN", navSupport:"UNTERSTÜTZUNG", navContact:"KONTAKT",
    loginBtn:"ANMELDEN", logoutBtn:"Abmelden",
    heroBadge:"🌍 GLOBALE FAN-GEMEINSCHAFT",
    title:"Globale Fan-Gemeinschaft von Conejo Malo",
    subtitle:"Globale Fan-Gemeinschaft von Bad Bunny",
    heroDesc:"Feiert die Musik, Kultur und weltweite Wirkung von Bad Bunny. Schließ dich Millionen von Fans an.",
    statGlobal:"Globale Gemeinschaft", statVIP:"VIP-Zugang", statMusic:"Exklusive Inhalte",
    joinBtn:"Der Gemeinschaft beitreten", exploreBtn:"Erkunden",
    aboutTag:"ÜBER UNS", aboutTitle:"Über die Gemeinschaft",
    aboutText:"Eine globale Fan-Gemeinschaft zur Feier der Musik und Kultur von Bad Bunny.",
    aboutF1:"Exklusive Musik", aboutF1D:"Zugang zu exklusiven Inhalten und Playlists.",
    aboutF2:"Globales Netzwerk", aboutF2D:"Verbinde dich mit Fans aus der ganzen Welt.",
    aboutF3:"Fan-Rankings", aboutF3D:"Verdiene Abzeichen und steige in den Rängen auf.",
    aboutF4:"Veranstaltungszugang", aboutF4D:"Frühzeitiger Zugang zu Konzertankündigungen.",
    disclaimer:"⚠️ Unabhängige Fan-Gemeinschaft. Nicht offiziell mit Bad Bunny verbunden.",
    memberTag:"MITGLIEDSCHAFT", memberTitle:"Fan-Mitgliedschaftsplattform",
    memberSubtitle:"WO FANS SICH VERBINDEN, TEILEN UND ALS EINER SPRECHEN",
    memberDesc:"Nur nach Anmeldung zugänglich.",
    tierFree:"Kostenlos", allMembersGet:"Alle Mitglieder Erhalten",
    rankTitle:"Fan-Ranking-System", rankDesc:"Verdiene deinen Rang durch Gemeinschaftsbeteiligung!",
    mapTitle:"Globale Fan-Karte", mapDesc:"Unsere Gemeinschaft umfasst alle Kontinente.",
    eventsTitle:"Fan-Veranstaltungen", eventsDesc:"Bleib mit Hörabenden und Diskussionen verbunden.",
    event1:"Hörabende", event1D:"Live-Album-Hörsitzungen mit der Gemeinschaft.",
    event2:"Fan-Wettbewerbe", event2D:"Kunstwettbewerbe, Lyrikkhallenges und Umfragen.",
    event3:"Konzertdiskussionen", event3D:"Live-Reaktions-Threads bei Konzerten.",
    supportTitle:"Unterstütze die Gemeinschaft", supportDesc:"Hilf dabei, diese Fan-Gemeinschaft am Leben zu erhalten.",
    cryptoMsg:"Kontakt für Adresse", emailSupport:"✉ Schreib uns eine E-Mail für Zahlungsanweisungen.",
    contactTitle:"Kontakt aufnehmen", contactDesc:"Fragen? Wende dich an das Team.",
    socialIG:"📸 Instagram", socialTT:"🎵 TikTok", socialFB:"👤 Facebook", socialX:"✖ X (Twitter)",
    modalTitle:"Mitglied Login / Registrierung", modalSub:"Tritt der globalen Fan-Gemeinschaft bei",
    emailLabel:"E-Mail", passLabel:"Passwort", registerBtn:"Registrieren", loginModalBtn:"Anmelden",
    modalTerms:"Mit dem Beitritt stimmst du unseren Gemeinschaftsrichtlinien zu."
  },
  ru: {
    navHome:"ГЛАВНАЯ", navCommunity:"СООБЩЕСТВО", navMembership:"ЧЛЕНСТВО",
    navEvents:"СОБЫТИЯ", navSupport:"ПОДДЕРЖКА", navContact:"КОНТАКТ",
    loginBtn:"ВОЙТИ", logoutBtn:"Выйти",
    heroBadge:"🌍 ГЛОБАЛЬНОЕ СООБЩЕСТВО ФАНАТОВ",
    title:"Глобальное Сообщество Фанатов Конехо Мало",
    subtitle:"Глобальное Сообщество Фанатов Бэд Банни",
    heroDesc:"Отмечаем музыку, культуру и мировое влияние Бэд Банни. Присоединяйтесь к миллионам фанатов.",
    statGlobal:"Глобальное Сообщество", statVIP:"VIP-доступ", statMusic:"Эксклюзивный Контент",
    joinBtn:"Присоединиться", exploreBtn:"Исследовать",
    aboutTag:"О НАС", aboutTitle:"О Сообществе",
    aboutText:"Глобальное сообщество фанатов, созданное для прославления музыки и культуры Бэд Банни.",
    aboutF1:"Эксклюзивная Музыка", aboutF1D:"Доступ к эксклюзивному контенту и плейлистам.",
    aboutF2:"Глобальная Сеть", aboutF2D:"Общайтесь с фанатами со всего мира.",
    aboutF3:"Рейтинги Фанатов", aboutF3D:"Зарабатывайте значки и поднимайтесь в рейтингах.",
    aboutF4:"Доступ к Событиям", aboutF4D:"Ранний доступ к анонсам концертов.",
    disclaimer:"⚠️ Независимое фан-сообщество. Не аффилировано официально с Бэд Банни.",
    memberTag:"ЧЛЕНСТВО", memberTitle:"Платформа Членства Фанатов",
    memberSubtitle:"ГДЕ ФАНАТЫ ОБЩАЮТСЯ, ДЕЛЯТСЯ И ГОВОРЯТ КАК ОДИН",
    memberDesc:"Доступно только после входа в систему.",
    tierFree:"Бесплатно", allMembersGet:"Все Члены Получают",
    rankTitle:"Система Рейтинга Фанатов", rankDesc:"Зарабатывайте свой ранг через участие в сообществе!",
    mapTitle:"Глобальная Карта Фанатов", mapDesc:"Наше сообщество охватывает все континенты.",
    eventsTitle:"События Фанатов", eventsDesc:"Оставайтесь на связи с прослушиваниями и обсуждениями.",
    event1:"Вечеринки Прослушивания", event1D:"Живые сессии прослушивания альбомов.",
    event2:"Конкурсы Фанатов", event2D:"Конкурсы искусства, задания по текстам и опросы.",
    event3:"Обсуждения Концертов", event3D:"Живые реакции во время концертов.",
    supportTitle:"Поддержите Сообщество", supportDesc:"Помогите сохранить это сообщество живым.",
    cryptoMsg:"Свяжитесь для адреса", emailSupport:"✉ Напишите нам для инструкций по оплате.",
    contactTitle:"Связаться с Нами", contactDesc:"Есть вопросы? Обратитесь к команде.",
    socialIG:"📸 Instagram", socialTT:"🎵 TikTok", socialFB:"👤 Facebook", socialX:"✖ X (Twitter)",
    modalTitle:"Вход / Регистрация", modalSub:"Присоединяйтесь к глобальному сообществу фанатов",
    emailLabel:"Эл. почта", passLabel:"Пароль", registerBtn:"Зарегистрироваться", loginModalBtn:"Войти",
    modalTerms:"Присоединившись, вы соглашаетесь с нашими правилами."
  },
  ja: {
    navHome:"ホーム", navCommunity:"コミュニティ", navMembership:"会員資格",
    navEvents:"イベント", navSupport:"サポート", navContact:"連絡先",
    loginBtn:"ログイン", logoutBtn:"ログアウト",
    heroBadge:"🌍 グローバルファンコミュニティ",
    title:"コネホ・マロのグローバルファンコミュニティ",
    subtitle:"バッド・バニーのグローバルファンコミュニティ",
    heroDesc:"バッド・バニーの音楽、文化、世界的影響を祝います。世界中の何百万人ものファンに参加しよう。",
    statGlobal:"グローバルコミュニティ", statVIP:"VIPアクセス", statMusic:"独占コンテンツ",
    joinBtn:"コミュニティに参加", exploreBtn:"探索",
    aboutTag:"私たちについて", aboutTitle:"コミュニティについて",
    aboutText:"バッド・バニーの音楽と文化を祝うために作られたグローバルファンコミュニティ。",
    aboutF1:"独占音楽", aboutF1D:"独占コンテンツとプレイリストにアクセス。",
    aboutF2:"グローバルネットワーク", aboutF2D:"世界中のファンとつながろう。",
    aboutF3:"ファンランキング", aboutF3D:"バッジを獲得してランクアップ。",
    aboutF4:"イベントアクセス", aboutF4D:"コンサートの発表への早期アクセス。",
    disclaimer:"⚠️ 独立したファンコミュニティ。バッド・バニーとは公式に提携していません。",
    memberTag:"会員資格", memberTitle:"ファン会員プラットフォーム",
    memberSubtitle:"ファンが繋がり、共有し、一つとして語るところ",
    memberDesc:"ログイン後のみアクセス可能。",
    tierFree:"無料", allMembersGet:"全会員が受け取るもの",
    rankTitle:"ファンランキングシステム", rankDesc:"コミュニティ参加でランクを獲得！",
    mapTitle:"グローバルファンマップ", mapDesc:"私たちのコミュニティはすべての大陸に広がっています。",
    eventsTitle:"ファンイベント", eventsDesc:"リスニングパーティーや議論でつながろう。",
    event1:"リスニングパーティー", event1D:"コミュニティとのライブアルバム鑑賞セッション。",
    event2:"ファンコンテスト", event2D:"アートコンテスト、歌詞チャレンジ、投票。",
    event3:"コンサートディスカッション", event3D:"コンサート中のライブリアクションスレッド。",
    supportTitle:"コミュニティをサポート", supportDesc:"このファンコミュニティを維持するのに役立てください。",
    cryptoMsg:"アドレスについてはお問い合わせください", emailSupport:"✉ 支払い指示についてはメールでお問い合わせください。",
    contactTitle:"お問い合わせ", contactDesc:"質問がありますか？チームにお問い合わせください。",
    socialIG:"📸 Instagram", socialTT:"🎵 TikTok", socialFB:"👤 Facebook", socialX:"✖ X (Twitter)",
    modalTitle:"会員ログイン / 登録", modalSub:"グローバルファンコミュニティに参加",
    emailLabel:"メール", passLabel:"パスワード", registerBtn:"登録", loginModalBtn:"ログイン",
    modalTerms:"参加することで、コミュニティガイドラインに同意します。"
  },
  zh: {
    navHome:"首页", navCommunity:"社区", navMembership:"会员",
    navEvents:"活动", navSupport:"支持", navContact:"联系",
    loginBtn:"登录", logoutBtn:"退出",
    heroBadge:"🌍 全球粉丝社区",
    title:"坏兔子全球粉丝社区",
    subtitle:"坏兔子全球粉丝社区",
    heroDesc:"庆祝坏兔子的音乐、文化和全球影响。加入全球数百万粉丝。",
    statGlobal:"全球社区", statVIP:"VIP访问", statMusic:"独家内容",
    joinBtn:"加入社区", exploreBtn:"探索",
    aboutTag:"关于我们", aboutTitle:"关于社区",
    aboutText:"一个为庆祝坏兔子的音乐和文化而创建的全球粉丝社区。",
    aboutF1:"独家音乐", aboutF1D:"访问独家内容和精选播放列表。",
    aboutF2:"全球网络", aboutF2D:"与来自世界各地的粉丝联系。",
    aboutF3:"粉丝排名", aboutF3D:"获得徽章并在排名中上升。",
    aboutF4:"活动访问", aboutF4D:"提前访问演唱会公告。",
    disclaimer:"⚠️ 独立粉丝社区。未正式隶属于坏兔子。",
    memberTag:"会员", memberTitle:"粉丝会员平台",
    memberSubtitle:"粉丝连接、分享和作为一个整体发声的地方",
    memberDesc:"仅在登录后可访问。",
    tierFree:"免费", allMembersGet:"所有会员获得",
    rankTitle:"粉丝排名系统", rankDesc:"通过社区参与获得你的排名！",
    mapTitle:"全球粉丝地图", mapDesc:"我们的社区遍布所有大洲。",
    eventsTitle:"粉丝活动", eventsDesc:"通过聆听派对和讨论保持联系。",
    event1:"聆听派对", event1D:"与社区一起的现场专辑聆听会。",
    event2:"粉丝竞赛", event2D:"艺术比赛、歌词挑战和投票。",
    event3:"演唱会讨论", event3D:"演唱会期间的实时反应帖子。",
    supportTitle:"支持社区", supportDesc:"帮助保持这个粉丝社区的活力和发展。",
    cryptoMsg:"联系获取地址", emailSupport:"✉ 发送电子邮件获取付款说明。",
    contactTitle:"联系我们", contactDesc:"有问题吗？联系团队。",
    socialIG:"📸 Instagram", socialTT:"🎵 TikTok", socialFB:"👤 Facebook", socialX:"✖ X (Twitter)",
    modalTitle:"会员登录 / 注册", modalSub:"加入全球粉丝社区",
    emailLabel:"电子邮件", passLabel:"密码", registerBtn:"注册", loginModalBtn:"登录",
    modalTerms:"加入即表示您同意我们的社区准则。"
  },
  ar: {
    navHome:"الرئيسية", navCommunity:"المجتمع", navMembership:"العضوية",
    navEvents:"الفعاليات", navSupport:"الدعم", navContact:"اتصل بنا",
    loginBtn:"تسجيل الدخول", logoutBtn:"تسجيل الخروج",
    heroBadge:"🌍 مجتمع المعجبين العالمي",
    title:"مجتمع معجبي كونيخو مالو العالمي",
    subtitle:"مجتمع معجبي باد باني العالمي",
    heroDesc:"نحتفل بموسيقى وثقافة وتأثير باد باني العالمي. انضم إلى ملايين المعجبين.",
    statGlobal:"مجتمع عالمي", statVIP:"وصول VIP", statMusic:"محتوى حصري",
    joinBtn:"انضم إلى المجتمع", exploreBtn:"استكشف",
    aboutTag:"من نحن", aboutTitle:"عن المجتمع",
    aboutText:"مجتمع عالمي للمعجبين تم إنشاؤه للاحتفال بموسيقى وثقافة باد باني.",
    aboutF1:"موسيقى حصرية", aboutF1D:"الوصول إلى المحتوى الحصري والقوائم.",
    aboutF2:"شبكة عالمية", aboutF2D:"تواصل مع المعجبين من جميع أنحاء العالم.",
    aboutF3:"تصنيفات المعجبين", aboutF3D:"اكسب شارات وارتقِ في التصنيفات.",
    aboutF4:"الوصول إلى الفعاليات", aboutF4D:"وصول مبكر إلى إعلانات الحفلات.",
    disclaimer:"⚠️ مجتمع مستقل للمعجبين. غير مرتبط رسمياً بباد باني.",
    memberTag:"العضوية", memberTitle:"منصة عضوية المعجبين",
    memberSubtitle:"حيث يتواصل المعجبون ويتشاركون ويتحدثون كواحد",
    memberDesc:"يمكن الوصول إليه فقط بعد تسجيل الدخول.",
    tierFree:"مجاني", allMembersGet:"جميع الأعضاء يحصلون على",
    rankTitle:"نظام تصنيف المعجبين", rankDesc:"اكسب مرتبتك من خلال المشاركة في المجتمع!",
    mapTitle:"خريطة المعجبين العالمية", mapDesc:"مجتمعنا يمتد عبر جميع القارات.",
    eventsTitle:"فعاليات المعجبين", eventsDesc:"ابق على تواصل مع حفلات الاستماع والمناقشات.",
    event1:"حفلات الاستماع", event1D:"جلسات استماع مباشرة للألبومات.",
    event2:"مسابقات المعجبين", event2D:"مسابقات فنية وتحديات كلمات واستطلاعات.",
    event3:"مناقشات الحفلات", event3D:"خيوط ردود الفعل المباشرة أثناء الحفلات.",
    supportTitle:"ادعم المجتمع", supportDesc:"ساعد في إبقاء مجتمع المعجبين حياً.",
    cryptoMsg:"تواصل للحصول على العنوان", emailSupport:"✉ راسلنا للحصول على تعليمات الدفع.",
    contactTitle:"تواصل معنا", contactDesc:"هل لديك أسئلة؟ تواصل مع الفريق.",
    socialIG:"📸 إنستغرام", socialTT:"🎵 تيك توك", socialFB:"👤 فيسبوك", socialX:"✖ إكس (تويتر)",
    modalTitle:"تسجيل دخول / تسجيل العضو", modalSub:"انضم إلى مجتمع المعجبين العالمي",
    emailLabel:"البريد الإلكتروني", passLabel:"كلمة المرور", registerBtn:"تسجيل", loginModalBtn:"دخول",
    modalTerms:"بالانضمام توافق على إرشادات مجتمعنا."
  },
  hi: {
    navHome:"होम", navCommunity:"समुदाय", navMembership:"सदस्यता",
    navEvents:"कार्यक्रम", navSupport:"समर्थन", navContact:"संपर्क",
    loginBtn:"लॉगिन", logoutBtn:"लॉगआउट",
    heroBadge:"🌍 वैश्विक प्रशंसक समुदाय",
    title:"कोनेहो मालो का वैश्विक प्रशंसक समुदाय",
    subtitle:"बैड बनी का वैश्विक प्रशंसक समुदाय",
    heroDesc:"बैड बनी की संगीत, संस्कृति और वैश्विक प्रभाव का जश्न मनाते हैं। लाखों प्रशंसकों से जुड़ें।",
    statGlobal:"वैश्विक समुदाय", statVIP:"VIP एक्सेस", statMusic:"विशेष सामग्री",
    joinBtn:"समुदाय से जुड़ें", exploreBtn:"अन्वेषण करें",
    aboutTag:"हमारे बारे में", aboutTitle:"समुदाय के बारे में",
    aboutText:"बैड बनी की संगीत और संस्कृति का जश्न मनाने के लिए बनाया गया एक वैश्विक प्रशंसक समुदाय।",
    aboutF1:"विशेष संगीत", aboutF1D:"विशेष सामग्री और प्लेलिस्ट तक पहुंच।",
    aboutF2:"वैश्विक नेटवर्क", aboutF2D:"दुनिया भर के प्रशंसकों से जुड़ें।",
    aboutF3:"प्रशंसक रैंकिंग", aboutF3D:"बैज अर्जित करें और रैंकिंग में ऊपर चढ़ें।",
    aboutF4:"कार्यक्रम एक्सेस", aboutF4D:"संगीत कार्यक्रम की घोषणाओं तक प्रारंभिक पहुंच।",
    disclaimer:"⚠️ स्वतंत्र प्रशंसक समुदाय। बैड बनी के साथ आधिकारिक रूप से संबद्ध नहीं।",
    memberTag:"सदस्यता", memberTitle:"प्रशंसक सदस्यता प्लेटफ़ॉर्म",
    memberSubtitle:"जहाँ प्रशंसक जुड़ते हैं, साझा करते हैं और एक के रूप में बोलते हैं",
    memberDesc:"केवल लॉगिन के बाद सुलभ।",
    tierFree:"मुफ़्त", allMembersGet:"सभी सदस्यों को मिलता है",
    rankTitle:"प्रशंसक रैंकिंग प्रणाली", rankDesc:"समुदाय भागीदारी के माध्यम से अपनी रैंक अर्जित करें!",
    mapTitle:"वैश्विक प्रशंसक मानचित्र", mapDesc:"हमारा समुदाय सभी महाद्वीपों में फैला है।",
    eventsTitle:"प्रशंसक कार्यक्रम", eventsDesc:"सुनने की पार्टियों और चर्चाओं से जुड़े रहें।",
    event1:"सुनने की पार्टियाँ", event1D:"समुदाय के साथ लाइव एल्बम सुनने के सत्र।",
    event2:"प्रशंसक प्रतियोगिताएं", event2D:"कला प्रतियोगिताएं, गीत चुनौतियां और मतदान।",
    event3:"संगीत कार्यक्रम चर्चाएं", event3D:"संगीत कार्यक्रमों के दौरान लाइव प्रतिक्रिया।",
    supportTitle:"समुदाय का समर्थन करें", supportDesc:"इस प्रशंसक समुदाय को जीवित और बढ़ते रहने में मदद करें।",
    cryptoMsg:"पते के लिए संपर्क करें", emailSupport:"✉ भुगतान निर्देशों के लिए हमें ईमेल करें।",
    contactTitle:"संपर्क करें", contactDesc:"प्रश्न हैं? टीम से संपर्क करें।",
    socialIG:"📸 Instagram", socialTT:"🎵 TikTok", socialFB:"👤 Facebook", socialX:"✖ X (Twitter)",
    modalTitle:"सदस्य लॉगिन / पंजीकरण", modalSub:"वैश्विक प्रशंसक समुदाय से जुड़ें",
    emailLabel:"ईमेल", passLabel:"पासवर्ड", registerBtn:"पंजीकरण करें", loginModalBtn:"लॉगिन",
    modalTerms:"शामिल होकर आप हमारी सामुदायिक दिशानिर्देशों से सहमत हैं।"
  },
  ko: {
    navHome:"홈", navCommunity:"커뮤니티", navMembership:"멤버십",
    navEvents:"이벤트", navSupport:"지원", navContact:"연락처",
    loginBtn:"로그인", logoutBtn:"로그아웃",
    heroBadge:"🌍 글로벌 팬 커뮤니티",
    title:"코네호 말로 글로벌 팬 커뮤니티",
    subtitle:"배드 버니 글로벌 팬 커뮤니티",
    heroDesc:"배드 버니의 음악, 문화 및 전 세계적 영향을 축하합니다. 수백만 명의 팬들과 함께하세요.",
    statGlobal:"글로벌 커뮤니티", statVIP:"VIP 접근", statMusic:"독점 콘텐츠",
    joinBtn:"커뮤니티 참여", exploreBtn:"탐색",
    aboutTag:"우리에 대해", aboutTitle:"커뮤니티 소개",
    aboutText:"배드 버니의 음악과 문화를 기념하기 위해 만들어진 글로벌 팬 커뮤니티.",
    aboutF1:"독점 음악", aboutF1D:"독점 콘텐츠와 플레이리스트에 접근하세요.",
    aboutF2:"글로벌 네트워크", aboutF2D:"전 세계 팬들과 연결하세요.",
    aboutF3:"팬 랭킹", aboutF3D:"배지를 획득하고 랭킹을 올리세요.",
    aboutF4:"이벤트 접근", aboutF4D:"콘서트 발표에 조기 접근하세요.",
    disclaimer:"⚠️ 독립적인 팬 커뮤니티입니다. 배드 버니와 공식적으로 제휴되지 않았습니다.",
    memberTag:"멤버십", memberTitle:"팬 멤버십 플랫폼",
    memberSubtitle:"팬들이 연결하고, 공유하고, 하나로서 말하는 곳",
    memberDesc:"로그인 후에만 접근 가능합니다.",
    tierFree:"무료", allMembersGet:"모든 멤버가 받는 것",
    rankTitle:"팬 랭킹 시스템", rankDesc:"커뮤니티 참여를 통해 랭크를 획득하세요!",
    mapTitle:"글로벌 팬 맵", mapDesc:"우리 커뮤니티는 모든 대륙에 걸쳐 있습니다.",
    eventsTitle:"팬 이벤트", eventsDesc:"청취 파티와 토론으로 연결을 유지하세요.",
    event1:"청취 파티", event1D:"커뮤니티와 함께하는 라이브 앨범 청취 세션.",
    event2:"팬 대회", event2D:"아트 콘테스트, 가사 챌린지, 팬 투표.",
    event3:"콘서트 토론", event3D:"콘서트 중 라이브 반응 스레드.",
    supportTitle:"커뮤니티 지원", supportDesc:"이 팬 커뮤니티가 살아있고 성장하도록 도와주세요.",
    cryptoMsg:"주소는 문의하세요", emailSupport:"✉ 결제 안내는 이메일로 문의하세요.",
    contactTitle:"연락하기", contactDesc:"질문이 있으신가요? 팀에 연락하세요.",
    socialIG:"📸 Instagram", socialTT:"🎵 TikTok", socialFB:"👤 Facebook", socialX:"✖ X (Twitter)",
    modalTitle:"멤버 로그인 / 등록", modalSub:"글로벌 팬 커뮤니티에 참여하세요",
    emailLabel:"이메일", passLabel:"비밀번호", registerBtn:"등록", loginModalBtn:"로그인",
    modalTerms:"참여함으로써 커뮤니티 가이드라인에 동의합니다."
  },
  it: {
    navHome:"HOME", navCommunity:"COMUNITÀ", navMembership:"ISCRIZIONE",
    navEvents:"EVENTI", navSupport:"SUPPORTO", navContact:"CONTATTO",
    loginBtn:"ACCEDI", logoutBtn:"Esci",
    heroBadge:"🌍 COMUNITÀ GLOBALE DI FAN",
    title:"Comunità Globale di Fan di Conejo Malo",
    subtitle:"Comunità Globale di Fan di Bad Bunny",
    heroDesc:"Celebrando la musica, la cultura e l'impatto mondiale di Bad Bunny. Unisciti a milioni di fan.",
    statGlobal:"Comunità Globale", statVIP:"Accesso VIP", statMusic:"Contenuto Esclusivo",
    joinBtn:"Unisciti alla Comunità", exploreBtn:"Esplora",
    aboutTag:"CHI SIAMO", aboutTitle:"Sulla Comunità",
    aboutText:"Una comunità globale di fan creata per celebrare la musica e la cultura di Bad Bunny.",
    aboutF1:"Musica Esclusiva", aboutF1D:"Accedi a contenuti esclusivi e playlist.",
    aboutF2:"Rete Globale", aboutF2D:"Connettiti con fan da tutto il mondo.",
    aboutF3:"Classifiche dei Fan", aboutF3D:"Guadagna badge e sali nelle classifiche.",
    aboutF4:"Accesso agli Eventi", aboutF4D:"Accesso anticipato agli annunci dei concerti.",
    disclaimer:"⚠️ Comunità di fan indipendente. Non ufficialmente affiliata a Bad Bunny.",
    memberTag:"ISCRIZIONE", memberTitle:"Piattaforma di Iscrizione dei Fan",
    memberSubtitle:"DOVE I FAN SI CONNETTONO, CONDIVIDONO E PARLANO COME UNO",
    memberDesc:"Accessibile solo dopo il login.",
    tierFree:"Gratuito", allMembersGet:"Tutti i Membri Ricevono",
    rankTitle:"Sistema di Classifica dei Fan", rankDesc:"Guadagna il tuo grado attraverso la partecipazione!",
    mapTitle:"Mappa Globale dei Fan", mapDesc:"La nostra comunità si estende in tutti i continenti.",
    eventsTitle:"Eventi dei Fan", eventsDesc:"Rimani connesso con feste di ascolto e discussioni.",
    event1:"Feste di Ascolto", event1D:"Sessioni di ascolto di album in diretta.",
    event2:"Competizioni dei Fan", event2D:"Concorsi d'arte, sfide di testi e sondaggi.",
    event3:"Discussioni sui Concerti", event3D:"Thread di reazione in diretta durante i concerti.",
    supportTitle:"Supporta la Comunità", supportDesc:"Aiuta a mantenere questa comunità di fan viva e in crescita.",
    cryptoMsg:"Contatta per l'indirizzo", emailSupport:"✉ Scrivici per le istruzioni di pagamento.",
    contactTitle:"Contattaci", contactDesc:"Hai domande? Contatta il team.",
    socialIG:"📸 Instagram", socialTT:"🎵 TikTok", socialFB:"👤 Facebook", socialX:"✖ X (Twitter)",
    modalTitle:"Login / Registrazione Membro", modalSub:"Unisciti alla comunità globale di fan",
    emailLabel:"Email", passLabel:"Password", registerBtn:"Registrati", loginModalBtn:"Accedi",
    modalTerms:"Unendoti accetti le nostre linee guida della comunità."
  }
};

function setLanguage(code) {
  const lang = languages[code] || languages.en;
  document.querySelectorAll('[data-lang]').forEach(el => {
    const key = el.getAttribute('data-lang');
    if (lang[key]) el.textContent = lang[key];
  });
  // RTL support for Arabic
  document.documentElement.setAttribute('dir', code === 'ar' ? 'rtl' : 'ltr');
}

window.setLanguage = setLanguage;
// Load English by default
setLanguage('en');
